### ISSUE TITLE
Error while "Exсluding already existing"

### ISSUE THREAD

**Issue by alexeyboo** [vi3itor/lingualeoanki#19]
Debug info:
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-10-23 20:30:07

Caught exception:
Traceback (most recent call last):
  File "C:\Users\alexey\AppData\Roaming\Anki2\addons21\1411073333\gui.py", line 345, in download_words
    filtered = self.filter_words(words) if not self.checkBoxUpdateNotes.isChecked() else words
  File "C:\Users\alexey\AppData\Roaming\Anki2\addons21\1411073333\gui.py", line 366, in filter_words
    words = [word for word in words if not utils.is_duplicate(word.get('wordValue'))]
  File "C:\Users\alexey\AppData\Roaming\Anki2\addons21\1411073333\gui.py", line 366, in <listcomp>
    words = [word for word in words if not utils.is_duplicate(word.get('wordValue'))]
  File "C:\Users\alexey\AppData\Roaming\Anki2\addons21\1411073333\utils.py", line 218, in is_duplicate
    return True if get_duplicates(word_value) else False
  File "C:\Users\alexey\AppData\Roaming\Anki2\addons21\1411073333\utils.py", line 205, in get_duplicates
    note_dupes = collection.findNotes('en:"%s"' % word_value)
  File "anki\collection.py", line 453, in find_notes
  File "anki\rsbackend_gen.py", line 88, in search_notes
  File "anki\rsbackend.py", line 265, in _run_command
anki.rsbackend.InvalidInput: Invalid search - please check for typing mistakes.

**Comment by vi3itor** [comment]
Thanks! I'll check it out. 

From the first glance, it looks like there is a word (or sentence), containing symbols other than letters, numbers, spaces or quotes (either single `'` or double `"`). 

Anyway, we can do better, by catching the exception and showing a warning to the user about the word, which causes trouble.

**Comment by alexeyboo** [comment]
I really do have phrases containing `/`, `(`, `)`, and I would like to get them imported too

**Comment by vi3itor** [comment]
I made a fix. Please update the add-on, **restart Anki**, and check again. 

It should have been working correctly with `(`, `)`, `/` before. Now I also check for the backslash symbol `\`(I don't recommend using it anyway, because it has a special meaning). 
The other change: if there is any unexpected symbol, it will show the message to the user about what word to blame.

**Comment by alexeyboo** [comment]
![image](https://user-images.githubusercontent.com/16614578/97178562-b3000680-17a8-11eb-9e3f-4d46a13bd1c7.png)
Unfortunately, I can't find the word `"` neither in my Lingualeo dictionary nor my Lingualeo deck

**Comment by vi3itor** [comment]
I see. It looks like there's an empty word in Lingualeo. Empty literally means no English. I'll fix it then.

**Comment by vi3itor** [comment]
Hopefully, it's fixed. Could you please try again? Can't test it because I don't know how to add an empty word to Lingualeo. Probably, it happened when they migrated the database, or when the extension didn't work correctly. 

I remember the day, when entering an incorrect password on the website created a new user...

**Comment by alexeyboo** [comment]
Worked fine, thank you!
